# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy Maven Repo to GitHub Pages

on:
  push:
    branches:
      - main  # Se ejecuta cada vez que subes cambios a main

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # Configura credenciales para el servidor 'github' en ~/.m2/settings.xml
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, Pack, Javadoc and Landing Page
        run: |
              # 1. Generar binarios y estructura maven. Al ejecutar deploy, Maven ahora incluirá los JARs de javadoc y 
              # fuentes dentro de target/mvn-repo gracias a la configuración del POM
              mvn clean deploy
        
              # 2. Generar Javadoc
              mvn javadoc:javadoc
        
              # 3. Copiar nuestra plantilla como index.html principal
              cp repo-index.html target/mvn-repo/index.html

#      - name: Deploy to GitHub Pages branch
#        uses: jamesives/github-pages-deploy-action@v4
#        with:
#          token: ${{ secrets.GH_TOKEN }}
#          branch: gh-pages # Rama donde se guardarán los binarios
#          folder: target/mvn-repo # Carpeta generada por el comando mvn deploy

      - name: Publish to GitHub Packages
        run: mvn clean deploy -DuniqueVersion=false -Dmaven.source.useDefaultManifestFile=true -Dmaven.source.includePom=true -Dmaven.install.skip=true -DdeployAtEnd=true -DaltDeploymentRepository='github::default::https://maven.pkg.github.com/iesebre/DirectAccessFile'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
